version: '3.8'

services:
    app:
        container_name: "octane"
        build:
            context: ./
            dockerfile: ./.docker/octane/Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/
            - .docker/octane/docker-entrypoint.sh:/opt/docker-entrypoint.sh:ro
        networks:
            - octane
    nginx:
        container_name: ${NGINX_CONTAINER_NAME}
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - ${NGINX_EXTERNAL_PORT}:80
            - ${NGINX_SSL_EXTERNAL_PORT}:443
        volumes:
            - ./:/var/www/
            - .docker/nginx/:/etc/nginx/conf.d/
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - octane
networks:
    octane:
        name: octane
